version: "3.9"
services:
    database:
        image: postgres:12.6
        restart: always
        environment:
          - POSTGRES_PASSWORD=dmg
          - POSTGRES_DB=dmg
          - POSTGRES_USER=dmg