// <auto-generated />
namespace InspectionServer.Migrations

open System
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion
open Npgsql.EntityFrameworkCore.PostgreSQL.Metadata

[<DbContext(typeof<InspectionModel.InspectionsContext>)>]
type InspectionsContextModelSnapshot() =
    inherit ModelSnapshot()

    override this.BuildModel(modelBuilder: ModelBuilder) =
        modelBuilder

            .UseIdentityByDefaultColumns()
            .HasAnnotation("Relational:MaxIdentifierLength", 63)
            .HasAnnotation("ProductVersion", "5.0.6")
        |> ignore

        modelBuilder.Entity(
            "InspectionModel+inspections",
            (fun b ->

                b.Property<string>("retail").HasColumnType("text")
                |> ignore

                b
                    .Property<int>("lighting_rate")
                    .IsRequired()
                    .HasColumnType("integer")
                |> ignore

                b
                    .Property<int>("rooftop_rate")
                    .IsRequired()
                    .HasColumnType("integer")
                |> ignore

                b
                    .Property<int>("snow_rate")
                    .IsRequired()
                    .HasColumnType("integer")
                |> ignore

                b.HasKey("retail") |> ignore

                b.ToTable("Inspections") |> ignore

                )
        )
        |> ignore
