name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.6
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: dmg
          POSTGRES_USER: dmg
          POSTGRES_DB: dmg
          POSTGRES_PORT: 5432

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Lint codebase
        run: dotnet tool install -g fantomas-tool && fantomas --recurse --check .
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
